[package]
name = "pmacros"
version = "0.1.0"
authors = ["赵宇龙 <zhaoyulong@qianxin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "1.0.72"
quote = "1.0.9"
chrono = "0.4.19"